# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: write-service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13write-service.proto\"\xb3\x01\n\x0cWriteRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\x10\n\x08\x64ocument\x18\x02 \x01(\t\x12)\n\x06\x66ields\x18\x03 \x03(\x0b\x32\x19.WriteRequest.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a#\n\x05\x46ield\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"/\n\rWriteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2:\n\x0cWriteService\x12*\n\tWriteData\x12\r.WriteRequest\x1a\x0e.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'write_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEREQUEST_FIELDSENTRY']._loaded_options = None
  _globals['_WRITEREQUEST_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_WRITEREQUEST']._serialized_start=24
  _globals['_WRITEREQUEST']._serialized_end=203
  _globals['_WRITEREQUEST_FIELDSENTRY']._serialized_start=121
  _globals['_WRITEREQUEST_FIELDSENTRY']._serialized_end=166
  _globals['_WRITEREQUEST_FIELD']._serialized_start=168
  _globals['_WRITEREQUEST_FIELD']._serialized_end=203
  _globals['_WRITERESPONSE']._serialized_start=205
  _globals['_WRITERESPONSE']._serialized_end=252
  _globals['_WRITESERVICE']._serialized_start=254
  _globals['_WRITESERVICE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
